- name: Pythonの仮想環境を作成
  command: virtualenv /home/{{ ansible_ssh_user }}/{{ venv_name }} -p python{{python_version}} creates='/home/{{ ansible_ssh_user }}/{{ venv_name }}'

- stat: path=/home/{{ ansible_ssh_user }}/{{ app_name }}
  register: f

- name: （サンプル）サイト・プロジェクトをgit cloneする
  git:
    repo: git@github.com:{{ github_user }}/{{ app_name }}.git
    dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
    accept_hostkey: yes

- name: サイト構築に必要なパッケージをインストール。requirements.txtに列挙されている前提
  pip:
    requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
    virtualenv: /home/{{ ansible_ssh_user }}/{{ venv_name }}
    virtualenv_python: python{{python_version}}
