- name: サイトがインストールされているか確認するため、先ず、アクセスした結果をファイル落とす。
  get_url:
    url: http://{{inventory_hostname}}
    dest: /tmp/index.html

- name: 落としたファイルを開いてみる
  shell: cat /tmp/index.html
  register: html_contents

- name: あるはずのキーワードがあればOK
  when: html_contents.stdout.find('hello') != -1
  debug: msg="success!"
